### ISSUE TITLE
Leaderboard v0.2-b - Components, explorer and verification upgrades 

### ISSUE THREAD

**Issue by 0xjjpa** [hoprnet/hopr-leaderboard#161]
# Introduction

Please also see https://github.com/hoprnet/hopr-leaderboard/issues/142. The leaderboard had multiple issues during Wildhorn v1, that range from issues with the subgraph failing to fetch the actual data from our nodes, to our Ceramic-base indexer dropping users out. If that were not enough, the current leaderboard is struggling with legacy code and makes adding or improving things pretty hard.

As a result, we need to refactor some of the work in it, separate the leaderboard (as an application) and its components (as modules), fix the subgraph and find an alternative way to index our user's data.

# Goal

The main goals of this leaderboard version are three, each of them can be split into their own subtasks.

## Subgraph

- [x] #162
- [ ] Upgrade our toolchain to deploy multiple subgraphs per testnet
- [ ] Create a `@hopr-leaderboard/explorer` package to fetch subgraph data as component.

## Verification
- [ ] Isolate existing faucet and verification code to a `@hopr-leaderboard` package
- [ ] Remove Ceramic-based indexer for gathering all verification node records
- [ ] Propose on-chain data indexer for node verification data gathering
- [ ] Setup gas-relayer to allow gas payment of on-chain submission for users
- [ ] Update community about changes and update documentation to reflect this

## Leaderboard structure
- [ ] Convert the existing repository into a monorepo using yarn workspaces
- [ ] Update vercel deployment workflow to use the new setup for automatic deployment
- [ ] Add CI pipeline to test our components in isolation per branch and on merge

**Comment by 0xjjpa** [comment]
[ grooming ] no changes in this epic for now

**Comment by 0xjjpa** [comment]
As commented in [horpnet/hopr-devrel#57](https://github.com/hoprnet/hopr-devrel/issues/57), this is now moved to `icebox` due lack of updates and priority.
